import React from "react";
import "./../styles/globals.css";
import AOSInit from "@/utils/aos";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <AOSInit />
        {children}
      </body>
    </html>
  );
}
